server:
  port: 0

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:~/role;
      username: sa
      password: 

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:87
